name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      base_url: https://www.saucedemo.com/
      e_username: standard_user
      e_password: secret_sauce

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pytest pytest-playwright pytest-html
          python -m playwright install --with-deps

      - name: Run tests (generate reports)
        run: |
          pytest \
            --html=report.html --self-contained-html \
            --junitxml=pytest-junit.xml \
            --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            report.html
            pytest-junit.xml
            artifacts/**     # your failure screenshots/html if any
          if-no-files-found: warn
